<?php
require_once('functions.php');
$page_content=include_template('index.php',[
'Cat'=>$Cat,
'Lots'=>$Lots,
]);
$layout_content=include_template('layout.php',[
'page_title'=>'Главная',
'is_auth'=>$is_auth,
'user_name'=>$user_name,
'page_content'=>$page_content,
'user_avatar'=>$user_avatar,
'Cat'=>$Cat
]);
print($layout_content);
?>